### ISSUE TITLE
Thanks!

### ISSUE THREAD

**Issue by trainerbill** [maxbeatty/dotenv-json#1]
Thanks for the quick publish!  I was actually just working on a module with a few differences that you may want to look at.

https://github.com/trainerbill/dotenv-json/blob/master/lib/index.js

Key differences:
* Stringify if the value is not a string.  https://github.com/trainerbill/dotenv-json/blob/master/lib/index.js#L20
* use app-root-path to easily get the application root.  process.cwd() isn't very reliable.
* filenames based on NODE_ENV

Let me know and I can submit a pr of anything you want to use out of this.

**Comment by trainerbill** [comment]
Not that I want to compete, but I have to have some functionality quickly.

https://github.com/trainerbill/dot-env-json

Up to you if you want to support dotenv-json or use mine.

**Comment by maxbeatty** [comment]
Sounds like you have a lot more needs than just reading JSON in a "dotenv" manner. Probably best to keep solving your own problems. I would just get in the way. Best of luck!
